Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 12:13:17
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 12:13:48
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 12:18:17
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 12:22:49
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 12:23:02
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 13:28:33
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-24 13:28:36
Exception details : System.Security; Key not valid for use in specified state.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-25 00:45:08
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-25 00:46:25
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-25 01:21:33
Exception details : mscorlib; Length of the data to decrypt is invalid.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-25 01:22:03
Exception details : mscorlib; Length of the data to decrypt is invalid.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-26 01:21:46
Exception details : mscorlib; Length of the data to decrypt is invalid.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-26 01:21:53
Exception details : mscorlib; Length of the data to decrypt is invalid.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-30 23:21:41
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-06-30 23:25:17
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-06-30 23:37:19
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-30 23:39:59
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-30 23:39:59
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-06-30 23:44:33
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-06-30 23:45:37
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-06-30 23:51:49
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-06-30 23:56:28
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 00:06:35
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 00:08:20
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 00:08:48
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 00:09:48
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 00:16:24
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 00:18:21
Exception details : mscorlib; Length of the data to decrypt is invalid.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 00:57:03
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 00:57:26
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:06:43
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:07:46
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:11:27
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:13:33
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:14:39
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:18:27
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:23:34
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:27:37
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:29:41
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:40:02
Exception details : EntityFramework; The operation cannot be completed because the DbContext has been disposed.
============================================================================================
Exception at: Test connection on :2017-07-01 01:42:19
Exception details : SimpleInjector; The container can't be changed after the first call to GetInstance, GetAllInstances and Verify. Please see https://simpleinjector.org/locked to understand why the container is locked. The following stack trace describes the location where the container was locked:

   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 30
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:48:25
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:48:50
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:49:37
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-01 01:50:36
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-01 01:50:41
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-02 13:39:08
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-02 13:40:11
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-02 14:54:26
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-02 15:03:13
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Đã có lỗi xảy ra khi đăng nhập, vui lòng thử lại sau on :2017-07-02 15:03:38
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at: Test connection on :2017-07-02 15:04:22
Exception details : System.Data.Entity; The underlying provider failed on Open.
============================================================================================
Exception at : private void txtShipmentIdOut_KeyDown(object sender, KeyEventArgs e) on :2017-07-19 23:05:36
Exception message : EntityFramework; An error occurred while updating the entries. See the inner exception for details.
Exception stacktrace : EntityFramework; at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at DataModel.UnitOfWork.UnitOfWork.SaveWinform() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\DataModel\UnitOfWork\UnitOfWork.cs:line 225
   at BusinessServices.ShipmentServices.Create(ShipmentEntity shipmentEntity) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\BusinessServices\ShipmentServices.cs:line 46
   at RapidWarehouse.FormXuat.txtShipmentIdOut_KeyDown(Object sender, KeyEventArgs e) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormXuat.cs:line 345
============================================================================================
Exception at : static void Main() on :2017-07-22 11:11:26
Exception message : SimpleInjector; Object reference not set to an instance of an object.
Exception stacktrace : SimpleInjector; at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstanceForRootType[TService]()
   at SimpleInjector.Container.GetInstance[TService]()
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : static void Main() on :2017-07-22 11:18:08
Exception message : SimpleInjector; Object reference not set to an instance of an object.
Exception stacktrace : SimpleInjector; at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstanceForRootType[TService]()
   at SimpleInjector.Container.GetInstance[TService]()
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : static void Main() on :2017-07-26 01:36:54
Exception message : System.Windows.Forms; Column named Shipment Id cannot be found.
Parameter name: columnName
Exception stacktrace : System.Windows.Forms; at System.Windows.Forms.DataGridViewCellCollection.get_Item(String columnName)
   at RapidWarehouse.FormXuat.DeleteRowFromGridview(DataGridView grv, DataGridViewCellEventArgs e, Int32 grvType) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormXuat.cs:line 511
   at RapidWarehouse.FormXuat.grvShipmentListOut_CellClick(Object sender, DataGridViewCellEventArgs e) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormXuat.cs:line 170
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : static void Main() on :2017-07-26 02:37:04
Exception message : RapidWarehouse; Object reference not set to an instance of an object.
Exception stacktrace : RapidWarehouse; at RapidWarehouse.FormXuat.SaveShipmentOut() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormXuat.cs:line 142
   at RapidWarehouse.FormXuat.btnOpenBoxOut_Click(Object sender, EventArgs e) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormXuat.cs:line 336
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : static void Main() on :2017-07-26 04:11:47
Exception message : EntityFramework; An error occurred while updating the entries. See the inner exception for details.
Exception stacktrace : EntityFramework; at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at DataModel.UnitOfWork.UnitOfWork.SaveWinform() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\DataModel\UnitOfWork\UnitOfWork.cs:line 236
   at BusinessServices.EmployeeServices.CreateOrUpdateEmployee(EmployeeEntity employee) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\BusinessServices\EmployeeServices.cs:line 49
   at RapidWarehouse.FormCreateEditEmployee.btnSave_Click(Object sender, EventArgs e) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormCreateEditEmployee.cs:line 88
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : static void Main() on :2017-07-27 02:13:38
Exception message : BusinessServices; Object reference not set to an instance of an object.
Exception stacktrace : BusinessServices; at BusinessServices.ShipmentServices.<>c__DisplayClass7_0.<SearchByConditions>b__0(ShipmentInfor t) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\BusinessServices\ShipmentServices.cs:line 99
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at DataModel.GenericRepository.GenericRepository`1.Get(Func`2 where) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\DataModel\GenericRepository\GenericRepository.cs:line 179
   at BusinessServices.ShipmentServices.SearchByConditions(String shipmentId, String sotk, String sender, String receiver) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\BusinessServices\ShipmentServices.cs:line 99
   at RapidWarehouse.FormHaiQuanView.btnSearch_Click(Object sender, EventArgs e) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormHaiQuanView.cs:line 90
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : Test connection on :2017-07-27 09:09:33
Exception message : System.Data.Entity; The underlying provider failed on Open.
Exception stacktrace : System.Data.Entity; at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DataModel.GenericRepository.GenericRepository`1.GetAll() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\DataModel\GenericRepository\GenericRepository.cs:line 200
   at BusinessServices.EmployeeServices.GetAll() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\BusinessServices\EmployeeServices.cs:line 103
   at RapidWarehouse.FormConfigDB.btnTestConnection_Click(Object sender, EventArgs e) in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\FormConfigDB.cs:line 38
============================================================================================
Exception at : static void Main() on :2017-07-27 10:56:15
Exception message : System.Windows.Forms; Cannot access a disposed object.
Object name: 'FormLogin'.
Exception stacktrace : System.Windows.Forms; at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
Exception at : static void Main() on :2017-07-27 11:03:22
Exception message : System.Windows.Forms; Cannot access a disposed object.
Object name: 'FormLogin'.
Exception stacktrace : System.Windows.Forms; at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at RapidWarehouse.Program.Main() in C:\Projects Data\RapidLogisticsSolution\RapidLogistics Solution\RapidWarehouse\Program.cs:line 32
============================================================================================
